### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/iknowAmerica#4]
Please check out https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub and transfer this repo to https://github.com/sugarlabs :)

**Comment by AlanJAS** [comment]
I try to transfer and gets an error "You don’t have admin rights to sugarlabs".
Can you give me permissions?

**Comment by davelab6** [comment]
Sure! Please try now :)
