### ISSUE TITLE
Reservoir of Sura

### ISSUE THREAD

**Issue by leonardcj** [sugarlabs/iknowAmerica#5]
recursos/0venezuela/datos/levels.py:139 

Reservoir of Sura is referenced but it doesn't show up in Google searches.  Can someone confirm that this is  correct?

**Comment by AlanJAS** [comment]
Seems wrong.. The actual name is 'Guri'

https://en.wikipedia.org/wiki/Guri_Dam

https://es.wikipedia.org/wiki/Embalse_de_Guri



________________________________
De: leonardcj <notifications@github.com>
Enviado: martes, 21 de febrero de 2017 15:44
Para: sugarlabs/iknowAmerica
Cc: Subscribed
Asunto: [sugarlabs/iknowAmerica] Reservoir of Sura (#5)


recursos/0venezuela/datos/levels.py:139

Reservoir of Sura is referenced but it doesn't show up in Google searches. Can someone confirm that this is correct?
